### PR TITLE
Use PlayerPreLoginEvent instead.

### PR DESCRIPTION
**Pull request by ItzBulkDev**

### CODE REVIEW

**Comment by xxFlare** [comment]
It's a bad practice to use PlayerPreLoginEvent, also causes more lag,

**Comment by AndreyNazarchuk** [comment]
Yes but using playerPreLoginEvent makes the player transfer before the building terrain text, thus a more smooth experience for the player.

**Comment by xxFlare** [comment]
@AndreyNazarchuk Wait - It does?

**Comment by AndreyNazarchuk** [comment]
Yes. I am absolutely sure of it.

**Comment by ItzBulkDev** [comment]
It makes it so when they try to join, it wont connect then join a server. It will choose a server before it joins main

**Comment by xxFlare** [comment]
Hmm, Ill add it for now.

**Comment by xxFlare** [comment]
Well, if the server if offline or there is an error, i think PlayerJoinEvent will be better.

**Comment by xxFlare** [comment]
Ill re-open this when it comes to deciding.

**Pull request closed without merging**
